### ISSUE TITLE
Now is 2023 year, please deprecated TDEA(Triple Data Encryption Algorithm), backup source code only!

### ISSUE THREAD

**Issue by Twilight-Dream-Of-Magic** [Jemtaly/CryptoXX#2]
Three-key TDEA encryption and decryption
Effective as of the final publication of this revision of SP 800-131A, encryption using three-key TDEA is deprecated through December 31, 2023, using the approved encryption modes. Note that SP 800-67 specifies a restriction on protecting no more than 220 data blocks using the same single key bundle. Three-key TDEA may continue to be used for encryption in existing applications but shall not be used for encryption in new applications. After December 31, 2023, three-key TDEA is disallowed for encryption unless specifically allowed by other [NIST](https://www.encryptionconsulting.com/education-center/nist/) guidance. Decryption using three-key TDEA is allowed for legacy use.

Reference:
https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-131Ar2.pdf

**Comment by Jemtaly** [comment]
Thanks for the heads up! This cryptographic library implements some algorithms that have been proven insecure/deprecated. This is because although they are no longer used in real-world scenarios, they are still used for some legacy purposes and are often used in areas such as cryptographic learning, research, etc., which are also among the scenarios for which this cryptobase is intended. So I will continue to update these codes, but I guess I will note in the comments that they are not recommended for use in real-world scenarios.
